Create folders recursively on rocksdb_open
holepunchto/librocksdb pull request #3
Opened 2024-10-21 23:31 UTC by yassernasc

2024-10-21 23:36 UTC, yassernasc commented
There's some problems with the `libpath` dependency, I had to patch those changes to be able to bypass the compiler errors reproduced on CI:

![image](https://github.com/user-attachments/assets/ce810df2-50d6-47b2-8d7c-78df6f2bab41)

2024-10-22 18:03 UTC, kasperisager requested changes

2024-10-22 18:03 UTC, kasperisager commented on src/rocksdb.cc
> +  step->handle = req;
As per my previous comment, the necessary data should all be defined in the `rocksdb_open_t` struct. A hint is that there's now a constant number (2) of unconditional `malloc()` calls, which is unnecessary.

2024-10-22 18:03 UTC, kasperisager commented on test/open-close.c
> +  e = rocksdb_open(&db, &open, "test/fixtures/create/folders/recursively/open-close.db", &options, on_open);
Let's add a separate test that specifically tests recursive directory creation.

2024-10-29 16:43 UTC, yassernasc commented on src/rocksdb.cc
> +}
That adjustment does the trick? https://github.com/holepunchto/librocksdb/pull/3/commits/7b3e3e7f1c88f7aa87ed6fe28a20da564719ab08

2024-11-01 13:36 UTC, kasperisager requested changes

2024-11-01 13:36 UTC, kasperisager commented on src/rocksdb.cc
> +  return uv_queue_work(db->loop, &req->worker, rocksdb__recursive_mkdir, NULL);
This still runs `uv_fs_mkdir()` from the thread pool, which isn't safe. It should run on the same thread that `rocksdb_open()` was called from.

2024-11-05 10:06 UTC, kasperisager approved these changes

2024-11-05 10:43 UTC, merged